### ISSUE TITLE
Memory leak needs investigation

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php-ext#88]
The ext has a definite memory leak; it can easily be identified using PHP 7.* series using `zend_execute_ex` override. Consider the following script:

```
<?php

class A {
  function b() {}
}

$a = new A();

//scoutapm_enable_instrumentation(true);

var_dump(exec("ps --pid " . getmypid() . " --no-headers -o rss"));
for ($i = 0; $i <= 10000000; $i++) {
    $a->b();
}
var_dump(exec("ps --pid " . getmypid() . " --no-headers -o rss"));
```

Running this, I might see:

```
string(5) "24444"
string(5) "24572"
```

However, if I uncomment the `scoutapm_enable_instrumentation(true);` line to enable ScoutAPM - _even though we are not actually instrumenting b()_ there is still memory consumed:

```
string(5) "24308"
string(6) "336996"
```

This more than likely contributed to #87

**Comment by koko-bap** [comment]
Same issue here, with the extension enabled php-fpm memory usage grows by roughly +0.5GB on every request quickly eating up all available memory. PHP7.4, Centos8, scoutapm v1.4.0 via pecl.

**Comment by asgrim** [comment]
Thanks @koko-bap, I'll take a look into this soon :+1:

**Comment by asgrim** [comment]
@koko-bap I've just released [1.4.1](https://github.com/scoutapp/scout-apm-php-ext/releases/tag/1.4.1) which should fix this. Please let me know how you get on.

**Comment by koko-bap** [comment]
I can confirm the experienced memory leak is no longer an issue with 1.4.2! Thank you very much!

**Comment by asgrim** [comment]
> I can confirm the experienced memory leak is no longer an issue with 1.4.2! Thank you very much!

Thank you so much for reporting back! 🎉
